export type LessonStep={number:string;title:string;description:string;topics?:string[]};
export type LessonLink={title:string;description:string;url:string;label:string};
export type LessonMaterial={title:string;description:string;url?:string;label?:string};
export type Lesson={id:number;slug:string;title:string;category:string;hook:string;description:string;coverImage:string;lessonUrl:string;accentColor:string;teacherFiles:unknown[];studentFiles:unknown[];apps:unknown[];videos:unknown[];externalLinks:unknown[];tags:string[];order:number;grade?:string;duration?:string;about?:string[];objectives?:string[];steps?:LessonStep[];discussionQuestions?:string[];digitalTools?:LessonLink[];materials?:LessonMaterial[]};
export const lessons:Lesson[]=[
{id:1,slug:"identity-and-belonging",title:"אני ישראלי – סיפור של זהות ושייכות",category:"זהות ושייכות",hook:"מה הופך אותנו לישראלים, ומה מחבר בין הסיפורים השונים שלנו?",description:"שיעור פתיחה המזמין את התלמידים לבחון את מרכיבי הזהות הישראלית, את תחושת השייכות ואת המפגש בין זהות אישית, משפחתית, יהודית, קהילתית ולאומית.",coverImage:"/lesson-identity.png",lessonUrl:"https://canva.link/rqsnk0igagzoq06",accentColor:"#20A6A2",teacherFiles:[],studentFiles:[],apps:[],videos:[],externalLinks:[],tags:["זהות","שייכות"],order:1},
{id:2,slug:"jewish-bookshelf",title:"ארון הספרים היהודי",category:"זהות, מסורת ותרבות",hook:"מהם הרעיונות הגדולים של חגי תשרי, וכיצד הם נוגעים בחיים שלנו היום?",description:"שיעור המזמין את התלמידים להכיר את ארון הספרים היהודי דרך הרעיונות והערכים של חגי תשרי, ולבחון את הרלוונטיות שלהם לזהות האישית, לחברה ולחיים בישראל.",coverImage:"/lesson-jewish-bookshelf.png",lessonUrl:"https://www.canva.com/design/DAHVGxK95HE/_PByzJnPbNrPO7-cD62Jyg/view?utm_content=DAHVGxK95HE&utm_campaign=designshare&utm_medium=link&utm_source=viewer",accentColor:"#6F8F78",teacherFiles:[],studentFiles:[],apps:[],videos:[],externalLinks:[],tags:["יהדות","חגי תשרי"],order:2},
{id:3,slug:"tanks-and-courage",title:"מטנקי עמק הבכא לטנקיסטיות בחולית",category:"מורשת קרב ואחריות",hook:"מסיפורי הגבורה של מלחמת יום הכיפורים אל גבורת שבעה באוקטובר.",description:"מסע בין שני סיפורי לחימה מתקופות שונות, הבוחן אומץ, מנהיגות, אחריות אישית ורוח לחימה ברגעים שבהם יחידים וקבוצות נדרשו לפעול בתנאים קשים ולהגן על אחרים.",coverImage:"/lesson-tanks.png",lessonUrl:"https://canva.link/fr532x7l0msgdh2",accentColor:"#1D5573",teacherFiles:[],studentFiles:[],apps:[],videos:[],externalLinks:[],tags:["מורשת קרב","אחריות"],order:3},
{id:4,slug:"startup-nation",title:"אם מדינה הייתה סטארט־אפ",category:"חדשנות ישראלית",hook:"מה צריך כדי להפוך חזון של מדינה למציאות — גם כשלא הכול מוכן?",description:"שיעור חווייתי המזמין את התלמידים לחשוב על הקמת מדינה כמו על הקמת סטארט־אפ.",coverImage:"/lesson-startup.png",lessonUrl:"https://canva.link/vvtsj22nnwlc0ir",accentColor:"#63B8A7",teacherFiles:[],studentFiles:[],apps:[],videos:[],externalLinks:[],tags:["חדשנות","יזמות"],order:4,grade:"י׳",duration:"90 דקות",about:["שיעור חווייתי המזמין את התלמידים לחשוב על הקמת מדינה כמו על הקמת סטארט־אפ: אילו משאבים דרושים, במה משקיעים קודם ומה עושים כשלא הכול מוכן.","דרך הפעילות של „קהילת אופק” עוברים התלמידים אל המציאות של היישוב היהודי ערב הקמת המדינה, בוחנים את מידת המוכנות להקמת מדינה ומתמודדים עם השאלה שהייתה ממשית במאי 1948: להכריז עכשיו או להמתין?"],objectives:["להבין מהם המרכיבים הדרושים להקמת מדינה.","לתרגל תעדוף משאבים, מסחר וקבלת החלטות.","לבחון את מידת המוכנות של היישוב היהודי ערב הקמת המדינה.","לדון בשאלה האם נכון לפעול גם כאשר לא כל התנאים מושלמים."],steps:[{number:"01",title:"אם מדינה הייתה סטארט־אפ",description:"פתיחה: מה צריך כדי להקים מדינה?"},{number:"02",title:"קהילת אופק מקימה מדינה",description:"פעילות קבוצתית של חלוקת תקציב, רכישת משאבים ומסחר בין הקבוצות."},{number:"03",title:"האם ישראל הייתה מוכנה להקמה?",description:"בחינת שמונה תחומים מרכזיים ערב הקמת המדינה:",topics:["שטח","אוכלוסייה","הנהגה","מוסדות","ביטחון","הכרה בין־לאומית","משאבים כלכליים","חינוך"]},{number:"04",title:"להכריז או להמתין?",description:"סקר כיתתי ודיון סביב ההחלטה להכריז על הקמת מדינת ישראל במאי 1948."},{number:"05",title:"סיכום",description:"מה אפשר ללמוד מהקמת המדינה על חזון, סיכון וקבלת החלטות?"}],discussionQuestions:["האם מדינה חייבת להיות מוכנה בכל התחומים לפני שמכריזים עליה?","מה היה התחום החזק ביותר ומה היה הסיכון הגדול ביותר ערב הקמת המדינה?","מתי נכון לקחת סיכון כדי להפוך חזון למציאות?"],digitalTools:[{title:"סקר כיתתי",description:"להכריז על המדינה במאי 1948 או להמתין?",url:"https://may-1948-class-poll.baranat.chatgpt.site/?poll=bc267c9e-287b-4cd3-8a18-fc7b61750f76&results=1&created=1",label:"לפתיחת הסקר"},{title:"מי רוצה להקים מדינה?",description:"משחק כיתתי מסכם בנושא הקמת המדינה.",url:"https://how-israel-was-born-quiz.baranat.chatgpt.site/",label:"לפתיחת המשחק"}],materials:[{title:"דפי פעילות להדפסה",description:"דפי הפעילות של „קהילת אופק” המלווים את הפעילות הקבוצתית בשיעור."},{title:"מצגת השיעור",description:"„אם מדינה הייתה סטארט־אפ”",url:"https://canva.link/vvtsj22nnwlc0ir",label:"לצפייה במצגת"}]},
{id:5,slug:"brothers-and-disputes",title:"כשאחים שוכחים – מחלוקות בעם",category:"מחלוקת והבית המשותף",hook:"איך מנהלים מחלוקת קשה מבלי לפרק את הבית המשותף?",description:"שיעור העוסק במחלוקות מכוננות בתולדות העם והמדינה ובוחן את הרגע שבו ויכוח רעיוני הופך לשבר, לצד האחריות לעצור, להציב גבולות ולשמור על החברה המשותפת.",coverImage:"/lesson-disputes.png",lessonUrl:"https://canva.link/pi6to8w9vrnfrro",accentColor:"#647985",teacherFiles:[],studentFiles:[],apps:[],videos:[],externalLinks:[],tags:["מחלוקת","אחריות"],order:5}
];
